'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, Bot, Calculator, Check, ChevronDown, CircleDollarSign, Flame, Landmark, Menu, PiggyBank, Search, ShieldCheck, Sparkles, TrendingUp, WalletCards, X } from 'lucide-react';

const calculators = [
  {name:'복리 계산기',desc:'투자 원금이 시간에 따라 얼마나 성장하는지 계산해요.',icon:TrendingUp,color:'green',tag:'인기',cat:'투자'},
  {name:'적립식 투자 계산기',desc:'매월 꾸준히 투자했을 때의 미래 자산을 확인해요.',icon:BarChart3,color:'blue',tag:'추천',cat:'투자'},
  {name:'배당금 계산기',desc:'보유 주식과 배당률로 연간·월간 배당금을 계산해요.',icon:CircleDollarSign,color:'amber',tag:'인기',cat:'투자'},
  {name:'FIRE 계산기',desc:'경제적 자유를 위해 필요한 자산과 기간을 알아봐요.',icon:Flame,color:'red',tag:'',cat:'투자'},
  {name:'목표 자산 계산기',desc:'목표 금액까지 필요한 월 투자금과 기간을 계산해요.',icon:WalletCards,color:'purple',tag:'',cat:'투자'},
  {name:'CAGR 계산기',desc:'기간별 연평균 복합 성장률을 정확하게 계산해요.',icon:BarChart3,color:'cyan',tag:'',cat:'투자'},
  {name:'ETF 수익 계산기',desc:'ETF 투자 수익과 비용을 한 번에 비교해요.',icon:TrendingUp,color:'blue',tag:'',cat:'ETF'},
  {name:'리밸런싱 계산기',desc:'목표 비중에 맞춰 매수·매도 금액을 계산해요.',icon:Calculator,color:'purple',tag:'',cat:'ETF'},
  {name:'미국 배당 세후 계산기',desc:'원천징수 후 실제 받는 배당금을 확인해요.',icon:CircleDollarSign,color:'green',tag:'NEW',cat:'미국주식'},
  {name:'평균단가 계산기',desc:'추가 매수 후 달라지는 평균 매입가를 계산해요.',icon:BarChart3,color:'amber',tag:'',cat:'미국주식'},
  {name:'대출 계산기',desc:'상환 방식별 월 납입금과 총이자를 비교해요.',icon:Landmark,color:'blue',tag:'',cat:'금융'},
  {name:'연금 계산기',desc:'은퇴 후 받을 예상 연금과 준비 자금을 계산해요.',icon:PiggyBank,color:'green',tag:'',cat:'금융'},
];
const calculatorSlugs=['compound-interest','recurring-investment','dividend-calculator','fire-calculator','target-asset','cagr-calculator','etf-return','rebalancing'];

function formatWon(n:number){return Math.round(n).toLocaleString('ko-KR')+'원'}

export default function Home(){
 const [menu,setMenu]=useState(false); const [principal,setPrincipal]=useState(10000000); const [monthly,setMonthly]=useState(500000); const [rate,setRate]=useState(7); const [years,setYears]=useState(20);
 const result=useMemo(()=>{const m=rate/100/12, months=years*12; const factor=m===0?months:(Math.pow(1+m,months)-1)/m;const future=principal*Math.pow(1+m,months)+monthly*factor; const invested=principal+monthly*months; return {future,invested,profit:future-invested}},[principal,monthly,rate,years]);
 return <main>
  <header><div className="nav wrap"><a className="brand" href="/"><span className="brandmark"><TrendingUp size={20}/></span><span>Invest<span>Toolkit</span></span></a><nav><a href="/calculators">전체 계산기</a><a href="#guide">투자 가이드</a><a href="/saved">저장된 계산</a></nav><div className="navActions"><a className="search" href="/calculators"><Search size={18}/><span>계산기 검색</span></a><a className="primary small" href="/calculators">무료로 계산하기</a></div><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="mobileNav"><a href="/calculators">전체 계산기</a><a href="#guide">투자 가이드</a><a href="/saved">저장된 계산</a><a className="primary" href="/calculators">무료로 계산하기</a></div>}</header>

  <section className="hero"><div className="heroGlow"></div><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> 미국주식·ETF 투자 계산 도구</div><h1>미국주식 투자의 모든 계산을<br/><em>하나의 사이트에서.</em></h1><p>실제 미국 종목을 검색하고 현재가와 환율을 반영해<br className="desktop"/> 여러 종목의 원화 손익을 한 번에 계산합니다.</p><div className="usQuick"><a href="/us-portfolio">실제 종목 추가</a><a href="/calculators/us-stock-total-return">미국주식 수익</a><a href="/calculators/etf-expense-ratio">ETF 보수</a><a href="/calculators/dividend-income-goal">목표 배당</a></div><div className="heroCtas"><a className="primary" href="/us-portfolio">미국 종목 검색하기 <ArrowRight size={18}/></a><a className="secondary" href="/calculators"><Calculator size={18}/> 전체 계산기</a></div><div className="trust"><span><Check/>회원가입 없이 무료</span><span><Check/>시장 데이터 기준 표시</span><span><Check/>종목 계속 추가 가능</span></div></div>
  <div className="preview" id="calculator"><div className="previewTop"><div><span className="miniIcon"><TrendingUp/></span><div><strong>복리 계산기</strong><small>Compound Interest</small></div></div><a href="/calculators/compound-interest">전체 화면으로 계산 <ArrowRight/></a></div><div className="previewBody"><div className="fields"><label>초기 투자금<div><input value={principal} onChange={e=>setPrincipal(+e.target.value.replace(/\D/g,''))}/><span>원</span></div></label><label>월 투자금<div><input value={monthly} onChange={e=>setMonthly(+e.target.value.replace(/\D/g,''))}/><span>원</span></div></label><div className="fieldRow"><label>연 수익률<div><input value={rate} onChange={e=>setRate(+e.target.value)}/><span>%</span></div></label><label>투자 기간<div><input value={years} onChange={e=>setYears(+e.target.value)}/><span>년</span></div></label></div></div><div className="result"><span>{years}년 후 예상 자산</span><strong>{formatWon(result.future)}</strong><div className="resultGrid"><div><small>총 투자원금</small><b>{formatWon(result.invested)}</b></div><div><small>예상 수익</small><b className="up">+{formatWon(result.profit)}</b></div></div><div className="ai"><TrendingUp/><p><b>결과 한줄 해석</b><br/>투자 원금 대비 약 <strong>{(result.future/result.invested).toFixed(1)}배</strong>입니다. 수익률을 낮춰 보수적인 결과도 확인해 보세요.</p></div></div></div></div></div></section>

  <section className="stats"><div className="wrap"><div><strong>25</strong><span>투자·금융 계산기</span></div><div><strong>무료</strong><span>회원가입 없이 이용</span></div><div><strong>미국주식</strong><span>환율·배당·ETF 계산</span></div><div><strong>저장</strong><span>브라우저 결과 보관</span></div></div></section>

  <section className="tools section" id="tools"><div className="wrap"><div className="sectionHead"><div><span>CALCULATORS</span><h2>필요한 계산기를 찾아보세요</h2><p>투자부터 대출, 연금까지 금융 생활에 필요한 계산을 한곳에 모았습니다.</p></div><a href="/calculators">전체 계산기 보기 <ArrowRight/></a></div><div className="filters"><button className="active">전체</button><button>투자</button><button>ETF</button><button>미국주식</button><button>금융</button></div><div className="cardGrid">{calculators.slice(0,8).map((c,i)=><a className="toolCard" href={`/calculators/${calculatorSlugs[i]}`} key={c.name}><div className={`toolIcon ${c.color}`}><c.icon/></div>{c.tag&&<span className={`tag ${c.tag==='NEW'?'new':''}`}>{c.tag}</span>}<h3>{c.name}</h3><p>{c.desc}</p><span className="go">계산하기 <ArrowRight/></span></a>)}</div><a className="more" href="/calculators">20개 계산기 모두 보기 <ArrowRight/></a></div></section>

  <section className="difference section" id="insight"><div className="wrap diffGrid"><div><span className="sectionLabel">WHY INVESTTOOLKIT</span><h2>결과의 의미까지<br/>이해할 수 있는 계산기.</h2><p>InvestToolkit은 적용한 공식과 가정을 공개하고, 주요 조건이 달라질 때 결과가 어떻게 변하는지 비교합니다.</p><div className="features"><div><span><TrendingUp/></span><div><b>결과 해석</b><small>계산기별로 중요한 숫자의 의미를 설명합니다.</small></div></div><div><span><BarChart3/></span><div><b>시나리오 비교</b><small>기준 수익률 전후의 결과 차이를 비교합니다.</small></div></div><div><span><ShieldCheck/></span><div><b>공식과 가정 공개</b><small>계산에 사용한 공식과 한계를 함께 표시합니다.</small></div></div></div></div><div className="insightCard"><div className="insightHeader"><span><Sparkles/> Result Insight</span><small>복리 계산 결과</small></div><div className="asset"><span>예상 자산</span><strong>{formatWon(result.future)}</strong><small><TrendingUp/> 투자 원금 대비 {Math.round((result.future/result.invested-1)*100)}% 증가</small></div><div className="message"><TrendingUp/><p>예상 수익은 <b>{formatWon(result.profit)}</b>입니다. 수익률과 투자 기간을 낮춰 보수적인 결과도 비교해 보세요.</p></div><div className="impact"><div><span>확인할 조건</span><b className="down">수익률 변동</b></div><div><span>조정할 수 있는 조건</span><b className="up">월 투자금</b></div></div><a className="insightLink" href="/calculators/compound-interest">복리 계산기 자세히 보기 <ArrowRight/></a></div></div></section>

  <section className="guide section" id="guide"><div className="wrap"><div className="sectionHead"><div><span>LEARN & GROW</span><h2>계산과 함께 배우는 투자</h2><p>계산기의 원리부터 실전 활용법까지, 더 나은 결정을 위한 콘텐츠입니다.</p></div><a href="#">모든 가이드 보기 <ArrowRight/></a></div><div className="guideGrid"><article><div className="articleVisual v1"><span>COMPOUND<br/><b>INTEREST</b></span><TrendingUp/></div><div><span className="category">투자 기초</span><h3>복리의 마법, 10년 후 자산은 얼마나 달라질까?</h3><p>시간이 투자 수익에 미치는 영향을 실제 계산으로 알아봅니다.</p><small>7분 읽기 · 2026. 7. 8</small></div></article><article><div className="articleVisual v2"><Flame/><span>FIRE<br/><b>NUMBER</b></span></div><div><span className="category">FIRE</span><h3>내가 경제적 자유를 얻으려면 얼마가 필요할까?</h3><p>4% 룰과 생활비를 기준으로 나만의 FIRE 숫자를 계산해보세요.</p><small>9분 읽기 · 2026. 7. 5</small></div></article><article><div className="articleVisual v3"><CircleDollarSign/><span>DIVIDEND<br/><b>GROWTH</b></span></div><div><span className="category">배당 투자</span><h3>월 배당 100만원을 만드는 현실적인 투자 계획</h3><p>필요한 투자 원금과 배당 성장률을 단계별로 살펴봅니다.</p><small>8분 읽기 · 2026. 7. 2</small></div></article></div></div></section>

  <section className="cta"><div className="wrap"><Sparkles/><h2>더 나은 투자는, 정확한 계산에서 시작됩니다.</h2><p>지금 바로 무료 계산기로 당신의 투자 계획을 확인해보세요.</p><a className="primary light" href="#calculator">무료로 계산 시작하기 <ArrowRight/></a><small>회원가입 없이 모든 기본 계산기를 이용할 수 있습니다.</small></div></section>
  <footer><div className="wrap footerTop"><div><a className="brand" href="#"><span className="brandmark"><TrendingUp size={20}/></span><span>Invest<span>Toolkit</span></span></a><p>투자자의 모든 계산을 하나의 사이트에서.<br/>더 나은 금융 결정을 위한 스마트한 도구.</p></div><div className="footerLinks"><div><b>계산기</b><a href="/calculators">전체 계산기</a><a href="/calculators/etf-return">ETF 계산기</a><a href="/calculators/us-dividend-tax">미국주식 계산기</a><a href="/calculators/loan">금융 계산기</a></div><div><b>콘텐츠</b><a>투자 인사이트</a><a>초보자 가이드</a><a>용어 사전</a></div><div><b>서비스</b><a href="/saved">저장된 계산</a><a>서비스 소개</a><a>문의하기</a></div><div><b>법적 고지</b><a href="/terms">이용약관</a><a href="/privacy">개인정보처리방침</a><a href="/disclaimer">투자 유의사항</a></div></div></div><div className="wrap copyright"><span>© 2026 InvestToolkit. All rights reserved.</span><span>본 서비스는 투자 권유가 아닌 정보 제공을 목적으로 합니다.</span></div></footer>
 </main>
}
