'use client';
import {useMemo,useState} from 'react';
import {AlertCircle,Plus,RefreshCw,Search,Trash2,TrendingUp} from 'lucide-react';
type SearchItem={symbol:string;name:string;type:string;currency:string};type Position=SearchItem&{price:number;changePercent:number;latestTradingDay:string;quantity:number;averagePrice:number;buyFx:number};
const won=(n:number)=>`${Math.round(n).toLocaleString('ko-KR')}원`;const usd=(n:number)=>`$${n.toLocaleString('en-US',{maximumFractionDigits:2})}`;
export default function UsPortfolio(){const [query,setQuery]=useState('');const [results,setResults]=useState<SearchItem[]>([]);const [positions,setPositions]=useState<Position[]>([]);const [fx,setFx]=useState(1400);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const search=async(e:React.FormEvent)=>{e.preventDefault();if(!query.trim())return;setLoading(true);setError('');try{const r=await fetch(`/api/market/search?q=${encodeURIComponent(query)}`);const d=await r.json();if(!r.ok)throw new Error(d.error==='MARKET_API_KEY_REQUIRED'?'시장 데이터 API 키 연결이 필요합니다.':d.error==='MARKET_API_LIMIT'?'시장 데이터 호출 한도에 도달했습니다.':'종목 검색에 실패했습니다.');setResults(d.items)}catch(e){setError(e instanceof Error?e.message:'검색 오류')}finally{setLoading(false)}};
 const add=async(item:SearchItem)=>{if(positions.some(x=>x.symbol===item.symbol))return;setLoading(true);setError('');try{const r=await fetch(`/api/market/quote?symbol=${encodeURIComponent(item.symbol)}`);const d=await r.json();if(!r.ok)throw new Error(d.error==='MARKET_API_KEY_REQUIRED'?'시장 데이터 API 키 연결이 필요합니다.':'현재가를 불러오지 못했습니다.');setPositions(p=>[...p,{...item,price:d.price,changePercent:d.changePercent,latestTradingDay:d.latestTradingDay,quantity:1,averagePrice:d.price,buyFx:fx}]);setResults([]);setQuery('')}catch(e){setError(e instanceof Error?e.message:'현재가 조회 오류')}finally{setLoading(false)}};
 const update=(symbol:string,key:keyof Position,value:number)=>setPositions(p=>p.map(x=>x.symbol===symbol?{...x,[key]:value}:x));
 const totals=useMemo(()=>positions.reduce((a,p)=>{const cost=p.averagePrice*p.quantity*p.buyFx,value=p.price*p.quantity*fx;return{cost:a.cost+cost,value:a.value+value}}, {cost:0,value:0}),[positions,fx]);const profit=totals.value-totals.cost;
 return <div className="portfolioTool"><section className="portfolioSearch"><div><span>US STOCK & ETF SEARCH</span><h1>미국 종목을 검색하고<br/>포트폴리오에 추가하세요.</h1><p>티커 또는 회사명으로 검색하면 시장 데이터에서 현재가를 불러옵니다.</p></div><form onSubmit={search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: AAPL, Apple, VOO, SCHD"/><button disabled={loading}>{loading?<RefreshCw className="spin"/>:'검색'}</button></form>{error&&<div className="marketError"><AlertCircle/>{error}</div>}{results.length>0&&<div className="symbolResults">{results.map(x=><button onClick={()=>add(x)} key={x.symbol}><span><b>{x.symbol}</b><small>{x.name}</small></span><em>{x.type}</em><Plus/></button>)}</div>}</section>
 <section className="portfolioSummary"><div><span>현재 환율</span><label><input type="number" value={fx} onChange={e=>setFx(Number(e.target.value))}/> 원/USD</label></div><div><span>총 매입금액</span><b>{won(totals.cost)}</b></div><div><span>현재 평가금액</span><b>{won(totals.value)}</b></div><div><span>총손익</span><b className={profit>=0?'positive':'negative'}>{profit>=0?'+':''}{won(profit)}</b></div></section>
 <section className="positions"><div className="positionsHead"><div><h2>계산 종목</h2><p>계산 중에도 검색해 종목과 ETF를 계속 추가할 수 있습니다.</p></div><span>{positions.length}개</span></div>{positions.length===0?<div className="positionEmpty"><TrendingUp/><b>아직 추가한 종목이 없습니다.</b><p>위 검색창에서 미국주식 또는 ETF를 추가해 보세요.</p></div>:<div className="positionList">{positions.map(p=>{const cost=p.averagePrice*p.quantity*p.buyFx,value=p.price*p.quantity*fx,pnl=value-cost;return <article key={p.symbol}><div className="stockIdentity"><b>{p.symbol}</b><span>{p.name}</span><small>{p.type} · {p.latestTradingDay} 기준</small></div><div className="livePrice"><span>현재가</span><b>{usd(p.price)}</b><small className={p.changePercent>=0?'positive':'negative'}>{p.changePercent>=0?'+':''}{p.changePercent.toFixed(2)}%</small></div><label>보유수량<input type="number" value={p.quantity} min="0" step="0.0001" onChange={e=>update(p.symbol,'quantity',Number(e.target.value))}/></label><label>평균 매수가<input type="number" value={p.averagePrice} min="0" step="0.01" onChange={e=>update(p.symbol,'averagePrice',Number(e.target.value))}/></label><label>매수 환율<input type="number" value={p.buyFx} min="0" onChange={e=>update(p.symbol,'buyFx',Number(e.target.value))}/></label><div className="positionPnl"><span>원화 손익</span><b className={pnl>=0?'positive':'negative'}>{pnl>=0?'+':''}{won(pnl)}</b></div><button className="removePosition" onClick={()=>setPositions(x=>x.filter(v=>v.symbol!==p.symbol))}><Trash2/></button></article>})}</div>}</section><div className="marketNotice"><AlertCircle/><p>표시 가격은 Alpha Vantage 제공 데이터이며 실시간 또는 거래소 공식 체결가가 아닐 수 있습니다. 화면에 표시된 기준일을 확인하세요.</p></div></div>}
