export type Field={key:string;label:string;unit:string;default:number;min?:number;step?:number;options?:{label:string;value:number}[]};
export type CalculatorDef={slug:string;name:string;category:string;description:string;fields:Field[];formula:string;example:string;faqs:{q:string;a:string}[]};

const faq=(name:string)=>[
 {q:`${name} 결과는 정확한가요?`,a:'입력값과 표시된 가정을 기준으로 계산한 참고값입니다. 실제 세금, 수수료, 상품 조건에 따라 달라질 수 있습니다.'},
 {q:'수익률은 어떻게 입력해야 하나요?',a:'장기 계획에는 단기 최고 수익률보다 보수적인 기대수익률을 사용하는 것이 좋습니다.'},
];
export const calculators:CalculatorDef[]=[
 {slug:'compound-interest',name:'복리 계산기',category:'투자',description:'초기 투자금이 복리로 성장하는 미래 가치를 계산합니다.',fields:[{key:'principal',label:'초기 투자금',unit:'원',default:10000000},{key:'monthly',label:'정기 투자금',unit:'원',default:500000},{key:'rate',label:'연 수익률',unit:'%',default:7,step:.1},{key:'years',label:'투자 기간',unit:'년',default:20},{key:'frequency',label:'투자 주기',unit:'',default:12,options:[{label:'매월',value:12},{label:'분기마다',value:4},{label:'매년',value:1}]},{key:'timing',label:'납입 시점',unit:'',default:0,options:[{label:'기간 말',value:0},{label:'기간 초',value:1}]},{key:'inflation',label:'연 물가상승률',unit:'%',default:2,step:.1}],formula:'미래가치 = 초기 투자금의 복리 미래가치 + 정기 투자금의 미래가치. 납입 주기·시점과 물가상승률을 반영합니다.',example:'1,000만원을 시작으로 매월 50만원씩 연 7% 수익률로 20년 투자하는 경우',faqs:faq('복리 계산기')},
 {slug:'recurring-investment',name:'적립식 투자 계산기',category:'투자',description:'매월 일정 금액을 투자했을 때 예상 자산을 계산합니다.',fields:[{key:'monthly',label:'월 투자금',unit:'원',default:1000000},{key:'rate',label:'연 수익률',unit:'%',default:8,step:.1},{key:'years',label:'투자 기간',unit:'년',default:15}],formula:'적립 미래가치 = 월 투자금 × ((1 + 월수익률)^개월 - 1) ÷ 월수익률',example:'매월 100만원을 연 8%로 15년간 투자하는 경우',faqs:faq('적립식 투자 계산기')},
 {slug:'dividend-calculator',name:'배당금 계산기',category:'투자',description:'투자금과 배당수익률로 예상 배당금을 계산합니다.',fields:[{key:'principal',label:'투자금',unit:'원',default:50000000},{key:'yield',label:'배당수익률',unit:'%',default:4,step:.1},{key:'tax',label:'배당 세율',unit:'%',default:15.4,step:.1},{key:'frequency',label:'연 지급 횟수',unit:'',default:4,options:[{label:'매월 12회',value:12},{label:'분기 4회',value:4},{label:'반기 2회',value:2},{label:'연 1회',value:1}]},{key:'growth',label:'연 배당 성장률',unit:'%',default:5,step:.1},{key:'years',label:'예상 기간',unit:'년',default:10}],formula:'세후 배당금 = 투자금 × 배당수익률 × (1 - 세율). 지급 주기와 배당 성장률을 함께 표시합니다.',example:'5,000만원을 배당수익률 4%인 자산에 투자하는 경우',faqs:faq('배당금 계산기')},
 {slug:'dividend-growth',name:'배당 성장 계산기',category:'투자',description:'배당 성장률과 재투자를 반영한 미래 배당금을 계산합니다.',fields:[{key:'dividend',label:'현재 연 배당금',unit:'원',default:2000000},{key:'growth',label:'연 배당 성장률',unit:'%',default:6,step:.1},{key:'years',label:'기간',unit:'년',default:10}],formula:'미래 배당금 = 현재 배당금 × (1 + 배당 성장률)^기간',example:'연 배당금 200만원이 매년 6% 성장하는 경우',faqs:faq('배당 성장 계산기')},
 {slug:'fire-calculator',name:'FIRE 계산기',category:'투자',description:'경제적 자유에 필요한 목표 자산과 도달 기간을 계산합니다.',fields:[{key:'age',label:'현재 나이',unit:'세',default:35},{key:'expense',label:'월 생활비',unit:'원',default:3000000},{key:'otherIncome',label:'은퇴 후 월 기타소득',unit:'원',default:0},{key:'withdrawal',label:'안전 인출률',unit:'%',default:4,step:.1},{key:'current',label:'현재 투자자산',unit:'원',default:100000000},{key:'monthly',label:'월 투자금',unit:'원',default:1500000},{key:'rate',label:'연 수익률',unit:'%',default:7,step:.1},{key:'inflation',label:'연 물가상승률',unit:'%',default:2,step:.1}],formula:'FIRE 목표 = (연 생활비 - 연 기타소득) ÷ 안전 인출률. 예상 도달 나이와 실질수익률을 함께 계산합니다.',example:'월 생활비 300만원과 4% 인출률을 적용하는 경우',faqs:faq('FIRE 계산기')},
 {slug:'target-asset',name:'목표 자산 계산기',category:'투자',description:'목표 자산을 만들기 위해 필요한 월 투자금을 계산합니다.',fields:[{key:'target',label:'목표 자산',unit:'원',default:1000000000},{key:'current',label:'현재 자산',unit:'원',default:100000000},{key:'rate',label:'연 수익률',unit:'%',default:7,step:.1},{key:'years',label:'목표 기간',unit:'년',default:20}],formula:'필요 월 투자금 = (목표액 - 현재 자산의 미래가치) ÷ 적립 미래가치 계수',example:'현재 1억원에서 20년 후 10억원을 목표로 하는 경우',faqs:faq('목표 자산 계산기')},
 {slug:'cagr-calculator',name:'CAGR 계산기',category:'투자',description:'시작값과 종료값의 연평균 복합 성장률을 계산합니다.',fields:[{key:'start',label:'시작 금액',unit:'원',default:10000000},{key:'end',label:'최종 금액',unit:'원',default:20000000},{key:'years',label:'기간',unit:'년',default:5}],formula:'CAGR = (최종 금액 ÷ 시작 금액)^(1 ÷ 기간) - 1',example:'1,000만원이 5년 뒤 2,000만원이 된 경우',faqs:faq('CAGR 계산기')},
 {slug:'expected-return',name:'기대수익 계산기',category:'투자',description:'상승·기준·하락 시나리오의 확률 가중 기대수익을 계산합니다.',fields:[{key:'bull',label:'상승 시 수익률',unit:'%',default:20},{key:'bullP',label:'상승 확률',unit:'%',default:30},{key:'base',label:'기준 수익률',unit:'%',default:7},{key:'baseP',label:'기준 확률',unit:'%',default:50},{key:'bear',label:'하락 시 수익률',unit:'%',default:-15},{key:'principal',label:'투자금',unit:'원',default:10000000}],formula:'기대수익률 = 각 시나리오 수익률 × 발생 확률의 합',example:'상승·기준·하락 세 가지 가능성을 반영하는 경우',faqs:faq('기대수익 계산기')},
 {slug:'etf-return',name:'ETF 수익 계산기',category:'ETF',description:'ETF의 매매차익과 분배금을 합산한 총수익을 계산합니다.',fields:[{key:'buy',label:'매수가',unit:'원',default:50000},{key:'sell',label:'현재가',unit:'원',default:62000},{key:'quantity',label:'보유 수량',unit:'주',default:100},{key:'dividend',label:'주당 누적 분배금',unit:'원',default:1800}],formula:'총수익 = (현재가 - 매수가) × 수량 + 주당 분배금 × 수량',example:'5만원에 매수한 ETF 100주가 6만2천원이 된 경우',faqs:faq('ETF 수익 계산기')},
 {slug:'etf-dividend',name:'ETF 배당 계산기',category:'ETF',description:'ETF 분배금과 지급 주기에 따른 현금흐름을 계산합니다.',fields:[{key:'price',label:'ETF 가격',unit:'원',default:50000},{key:'quantity',label:'보유 수량',unit:'주',default:1000},{key:'yield',label:'연 분배율',unit:'%',default:5,step:.1},{key:'frequency',label:'연 지급 횟수',unit:'회',default:12}],formula:'회당 분배금 = 투자금 × 연 분배율 ÷ 지급 횟수',example:'5,000만원 상당 ETF의 연 분배율이 5%인 경우',faqs:faq('ETF 배당 계산기')},
 {slug:'rebalancing',name:'리밸런싱 계산기',category:'ETF',description:'두 자산을 목표 비중으로 맞추기 위한 조정 금액을 계산합니다.',fields:[{key:'assetA',label:'자산 A 현재 금액',unit:'원',default:70000000},{key:'assetB',label:'자산 B 현재 금액',unit:'원',default:30000000},{key:'targetA',label:'자산 A 목표 비중',unit:'%',default:60}],formula:'목표 금액 = 전체 자산 × 목표 비중',example:'7:3인 주식·채권 비중을 6:4로 조정하는 경우',faqs:faq('리밸런싱 계산기')},
 {slug:'exchange-rate',name:'환율 계산기',category:'미국주식',description:'원화와 달러 환전 금액 및 수수료를 계산합니다.',fields:[{key:'won',label:'환전할 원화',unit:'원',default:10000000},{key:'rate',label:'원·달러 환율',unit:'원',default:1380},{key:'fee',label:'환전 수수료율',unit:'%',default:.1,step:.01}],formula:'수령 달러 = 원화 ÷ 환율 × (1 - 수수료율)',example:'1,000만원을 환율 1,380원에 달러로 환전하는 경우',faqs:faq('환율 계산기')},
 {slug:'us-dividend-tax',name:'미국 배당 세후 계산기',category:'미국주식',description:'미국주식 배당금의 원천징수 후 수령액을 계산합니다.',fields:[{key:'usd',label:'세전 배당금',unit:'달러',default:2000},{key:'rate',label:'원·달러 환율',unit:'원',default:1380},{key:'tax',label:'원천징수율',unit:'%',default:15}],formula:'세후 배당 = 세전 배당 × (1 - 원천징수율)',example:'미국주식에서 연 2,000달러 배당을 받는 경우',faqs:faq('미국 배당 세후 계산기')},
 {slug:'average-price',name:'평균단가 계산기',category:'미국주식',description:'추가 매수 후 변경되는 평균 매입단가를 계산합니다.',fields:[{key:'price1',label:'기존 평균단가',unit:'원',default:50000},{key:'qty1',label:'기존 수량',unit:'주',default:100},{key:'price2',label:'추가 매수가',unit:'원',default:40000},{key:'qty2',label:'추가 수량',unit:'주',default:50}],formula:'새 평균단가 = 총 매입금액 ÷ 총 보유수량',example:'5만원에 100주 보유 중 4만원에 50주를 추가하는 경우',faqs:faq('평균단가 계산기')},
 {slug:'profit-loss',name:'손익 계산기',category:'미국주식',description:'매수가와 매도가를 기준으로 수익금과 수익률을 계산합니다.',fields:[{key:'buy',label:'매수가',unit:'원',default:50000},{key:'sell',label:'매도가',unit:'원',default:65000},{key:'quantity',label:'수량',unit:'주',default:100},{key:'fee',label:'총 비용률',unit:'%',default:.3,step:.01}],formula:'순손익 = 매도금액 - 매수금액 - 거래 비용',example:'5만원에 산 주식 100주를 6만5천원에 매도하는 경우',faqs:faq('손익 계산기')},
 {slug:'loan',name:'대출 계산기',category:'금융',description:'상환 방식별 월 상환금과 총이자를 계산합니다.',fields:[{key:'principal',label:'대출금',unit:'원',default:300000000},{key:'rate',label:'연 금리',unit:'%',default:4,step:.1},{key:'years',label:'상환 기간',unit:'년',default:30},{key:'repayment',label:'상환 방식',unit:'',default:0,options:[{label:'원리금균등',value:0},{label:'원금균등',value:1},{label:'만기일시상환',value:2}]},{key:'grace',label:'거치 기간',unit:'개월',default:0}],formula:'선택한 원리금균등·원금균등·만기일시상환 방식에 따라 첫 달 상환액과 총이자를 계산합니다.',example:'3억원을 연 4%로 30년간 상환하는 경우',faqs:faq('대출 계산기')},
 {slug:'deposit',name:'예금 계산기',category:'금융',description:'정기예금의 세전·세후 이자를 계산합니다.',fields:[{key:'principal',label:'예치금',unit:'원',default:50000000},{key:'rate',label:'연 금리',unit:'%',default:3.5,step:.1},{key:'months',label:'예치 기간',unit:'개월',default:12},{key:'tax',label:'이자소득세',unit:'%',default:15.4,step:.1}],formula:'세후 이자 = 원금 × 금리 × 기간 × (1 - 세율)',example:'5,000만원을 연 3.5%로 12개월 예치하는 경우',faqs:faq('예금 계산기')},
 {slug:'savings',name:'적금 계산기',category:'금융',description:'월 적립식 예금의 만기 수령액과 세후 이자를 계산합니다.',fields:[{key:'monthly',label:'월 납입금',unit:'원',default:500000},{key:'rate',label:'연 금리',unit:'%',default:4,step:.1},{key:'months',label:'납입 기간',unit:'개월',default:24},{key:'tax',label:'이자소득세',unit:'%',default:15.4,step:.1}],formula:'각 월 납입금의 예치 기간별 단리 이자를 합산',example:'매월 50만원씩 연 4% 적금에 24개월 납입하는 경우',faqs:faq('적금 계산기')},
 {slug:'severance',name:'퇴직금 계산기',category:'금융',description:'평균임금과 근속기간을 기준으로 예상 퇴직금을 계산합니다.',fields:[{key:'salary',label:'최근 3개월 임금 합계',unit:'원',default:12000000},{key:'days3m',label:'최근 3개월 총일수',unit:'일',default:92},{key:'serviceDays',label:'총 근속일수',unit:'일',default:1825}],formula:'퇴직금 = 1일 평균임금 × 30일 × (총 근속일수 ÷ 365)',example:'최근 3개월 임금 1,200만원, 근속기간 5년인 경우',faqs:faq('퇴직금 계산기')},
 {slug:'pension',name:'연금 계산기',category:'금융',description:'은퇴자산으로 받을 수 있는 예상 월 연금을 계산합니다.',fields:[{key:'asset',label:'은퇴 시점 자산',unit:'원',default:500000000},{key:'rate',label:'운용 수익률',unit:'%',default:4,step:.1},{key:'inflation',label:'연 물가상승률',unit:'%',default:2,step:.1},{key:'years',label:'수령 기간',unit:'년',default:25},{key:'monthlyIncome',label:'기타 월 연금',unit:'원',default:0}],formula:'월 연금 = 은퇴자산의 실질 운용수익률을 적용한 정액 인출액 + 기타 월 연금',example:'은퇴자산 5억원을 연 4%로 운용하며 25년간 수령하는 경우',faqs:faq('연금 계산기')},
];
export const getCalculator=(slug:string)=>calculators.find(c=>c.slug===slug);
