import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,ChevronRight,Info,TrendingUp} from 'lucide-react';
import CalculatorClient from '@/components/calculator-client';
import {calculators,getCalculator} from '@/lib/calculators';

export function generateStaticParams(){return calculators.map(c=>({slug:c.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=getCalculator(slug);if(!d)return{};return{title:`${d.name} | InvestToolkit`,description:d.description,alternates:{canonical:`/calculators/${slug}`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=getCalculator(slug);if(!d)notFound();const related=calculators.filter(x=>x.category===d.category&&x.slug!==d.slug).slice(0,3);const jsonLd={'@context':'https://schema.org','@type':'WebApplication',name:d.name,description:d.description,applicationCategory:'FinanceApplication',offers:{'@type':'Offer',price:'0',priceCurrency:'KRW'}};return <main className="calculatorPage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="calcHeader"><div className="wrap"><Link className="brand" href="/"><span className="brandmark"><TrendingUp size={20}/></span><span>Invest<span>Toolkit</span></span></Link><Link href="/#tools"><ArrowLeft/> 전체 계산기</Link></div></header><div className="calcHero"><div className="wrap"><div className="breadcrumb"><Link href="/">홈</Link><ChevronRight/><span>{d.category}</span><ChevronRight/><b>{d.name}</b></div><span className="calcCategory">{d.category} CALCULATOR</span><h1>{d.name}</h1><p>{d.description}</p></div></div><div className="wrap calcContent"><CalculatorClient def={d}/><div className="notice"><Info/><p><b>계산 결과 안내</b><br/>본 결과는 입력값을 기반으로 한 예상치이며 투자 권유가 아닙니다. 실제 결과는 시장 상황, 세금, 수수료 및 상품 조건에 따라 달라질 수 있습니다.</p></div><section className="contentSection"><h2>{d.name} 사용 방법</h2><p>각 입력란에 현재 조건과 예상 값을 입력하세요. 값을 변경할 때마다 결과가 자동으로 갱신됩니다. 장기 계획에는 지나치게 낙관적인 수치보다 보수적인 가정을 적용하는 것이 좋습니다.</p><div className="exampleBox"><b>계산 예시</b><p>{d.example}</p></div></section><section className="contentSection"><h2>계산 공식</h2><div className="formula">{d.formula}</div><p>계산 과정에서 소수점 반올림이 적용될 수 있습니다.</p></section><section className="contentSection"><h2>자주 묻는 질문</h2><div className="faqList">{d.faqs.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section><section className="contentSection"><h2>관련 계산기</h2><div className="relatedGrid">{related.map(x=><Link href={`/calculators/${x.slug}`} key={x.slug}><span>{x.category}</span><b>{x.name}</b><p>{x.description}</p><small>계산하기 <ChevronRight/></small></Link>)}</div></section></div></main>}

